import pandas as pd


class PreprocessingCnnHelper:
    @staticmethod
    def split_payload_bytes(
            df: pd.DataFrame,
            payload_col: str = 'payload_bytes',
            prefix: str = 'byte',
            fill_value: int = 0
    ) -> pd.DataFrame:
        """
        Converts lists of byte values from a DataFrame column into separate columns for CNN-compatible input

        Parameters:
        - df: Input DataFrame containing the payload data.
        - payload_col: Name of the column containing lists of byte values.
        - prefix: Prefix for the generated byte columns (e.g., 'byte_0', 'byte_1', ...).
        - fill_value: Value to fill in for shorter payloads (default is 0).
        """
        max_len = df[payload_col].apply(len).max()
        byte_cols = [f'{prefix}_{i}' for i in range(max_len)]
        df_bytes = pd.DataFrame(
            df[payload_col].tolist(),
            columns=byte_cols,
            index=df.index
        ).fillna(fill_value)
        return pd.concat([df, df_bytes], axis=1)
